# Generated by Django 3.2.25 on 2025-11-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userNoUsername', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLarder',
            fields=[
                ('url_ext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userNoUsername.usernamelessuser')),
                ('user_description', models.TextField()),
                ('cat1', models.CharField(max_length=30)),
                ('cat2', models.CharField(max_length=30)),
                ('discontinue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('estimated_expiration_date', models.DateField()),
                ('cat1_value', models.CharField(max_length=30)),
                ('cat2_value', models.CharField(max_length=30)),
                ('larder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='FMTAPIsPublic.userlarder')),
            ],
        ),
    ]
