# Generated by Django 3.2.25 on 2025-12-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FMTAPIsPublic', '0003_alter_fooditem_larder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlarder',
            old_name='url_ext',
            new_name='url_exten',
        ),
    ]
