# Generated by Django 3.2.25 on 2025-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMTAPIsPublic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='cat1_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='cat2_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
