# Generated by Django 3.2.25 on 2025-12-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMTAPIsPublic', '0002_auto_20251222_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='cat1_value',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='cat2_value',
            field=models.CharField(default='', max_length=30),
        ),
    ]
