# Generated by Django 6.0.1 on 2026-01-20 07:52

import FMTAPIsPublic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMTAPIsPublic', '0003_auto_20251222_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='estimated_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlarder',
            name='discontinue_date',
            field=models.DateField(default=FMTAPIsPublic.models.default_larder_expiration),
        ),
    ]
