# Generated by Django 6.0.2 on 2026-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMTAPIsPublic', '0004_alter_fooditem_estimated_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment_comment', models.CharField(max_length=2500)),
                ('comment_response', models.CharField(max_length=2500)),
                ('ok', models.BooleanField()),
                ('ingredients', models.ManyToManyField(to='FMTAPIsPublic.fooditem')),
            ],
        ),
    ]
